# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('heroMap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.HeroMap')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='total_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heromap',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Hero'),
        ),
        migrations.AddField(
            model_name='ally',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Hero'),
        ),
    ]
