# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20171031_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='heroMap',
            new_name='hero_map',
        ),
    ]
