# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20171031_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Map')),
            ],
        ),
    ]
