# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_maphero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='total_losses',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='total_wins',
            new_name='wins',
        ),
        migrations.AddField(
            model_name='heromap',
            name='slug',
            field=models.SlugField(default=b''),
        ),
    ]
