# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20171104_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromap',
            name='slug',
            field=models.SlugField(),
        ),
    ]
