# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20171106_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='cooldown',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
