# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_heromaptalent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='level',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='talent',
            name='losses',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='talent',
            name='wins',
            field=models.IntegerField(default=-1),
        ),
    ]
